server:
  port: 8080
spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      mvc:
        routes:
          - id: author-service
            uri: lb://AUTHORSERVICE
            predicates:
              - Path=/author/**
              - Method=GET
            filters:
              - RewritePath=/author/health, /health
              - SetPath=/author
          - id: book-service
            uri: lb://BOOKSERVICE
            predicates:
              - Path=/book/**
              - Method=GET
            filters:
              - RewritePath=/book/health, /health

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    console: '%msg%n'
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
