server:
  port: 8080
spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      mvc:
        routes:
          - id: author-service
            uri: lb://AUTHORSERVICE
            predicates:
              - Path=/authors/**
              - Method=GET
            filters:
              - RewritePath=/authors/health, /health
          - id: book-service
            uri: lb://BOOKSERVICE
            predicates:
              - Path=/books/**
              - Method=GET
            filters:
              - RewritePath=/books/health, /health

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    console: '%msg%n'
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
